# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/fedora-atomic"

  config.vm.provision :shell do |sh|
    sh.inline = <<-EOT
      sudo echo 'OPTIONS="--selinux-enabled --registry-mirror http://192.168.33.201:5000 --insecure-registry 192.168.33.201:5000"' > /etc/sysconfig/docker
      sudo systemctl restart docker
    EOT
  end
end
