# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos" # or "yungsang/coreos-beta", "yungsang/coreos-alpha"

  config.vm.box_version = ">= 1.3.6"

  config.vm.provision :file, source: "./registry.yml", destination: "/tmp/vagrantfile-user-data"

  config.vm.provision :shell do |sh|
    sh.inline = <<-EOT
      mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/
    EOT
  end
end
